### ISSUE TITLE
Rename "IgorPro" to "LanoreEtAl2019"?

### ISSUE THREAD

**Issue by sanjayankur31** [OpenSourceBrain/NWBShowcase#36]
For consistency? 

Note that this is used in NWB Explorer and so we'll also need to make a change there.

**Comment by pgleeson** [comment]
Initially that dir was just to test/demonstrate that IgorPro datasets could be loaded/converted, it just happened to be tested with data from ex SilverLabber Fred Lanore. Best to leave it as is, since there may be a few URLs pointing there, but it could certainly do with a README and some more pointers to the Biorxiv paper referenced in the nwb file...

**Comment by sanjayankur31** [comment]
Ah, right. I can add the read-me file. Do you know if this is all the data from the paper, or should the read me say something like "Example data set"?
